#lang racket
(require gigls/unsafe)
(define world (image-show (image-new 300 200)))

(define tommy (turtle-new world))
(define tanya (turtle-new world))
(define tucker (turtle-new world))

(turtle-up! tommy)
(turtle-forward! tommy 150)
(turtle-turn! tommy 90)
(turtle-forward! tommy 100)
(turtle-down! tommy)
(turtle-turn! tommy 90)
(turtle-forward! tommy 4)

(turtle-set-brush! tommy "2. Block 02")
(turtle-set-color! tommy "black")

(turtle-forward! tanya 50)
(turtle-set-color! tucker "red")
(turtle-forward! tucker 40)
(turtle-turn! tucker 90)
(turtle-forward! tucker 80)
(turtle-turn! tucker 90)
(turtle-forward! tucker 40)
(turtle-turn! tucker 90)
(turtle-forward! tucker 80)

(define turtle-center!
  (lambda (turtle)
    (turtle-teleport! turtle
                      (/ (image-width (turtle-world turtle)) 2)
                      (/ (image-height (turtle-world turtle)) 2))
    (turtle-face! turtle 0)))


(turtle-center! tommy)
(turtle-turn! tommy 90)
(turtle-forward! tommy 4)

(define figure02!
  (lambda (turtle)
    (turtle-forward! turtle 50)
    (turtle-turn! turtle 120)
    (turtle-forward! turtle 50)
    (turtle-turn! turtle 120)
    (turtle-turn! turtle 120)))

(turtle-center! tommy)
(figure02! tommy)
(figure02! tommy)
(figure02! tommy)
(figure02! tommy)
(repeat 3 figure02! tommy)
(repeat 3 figure02! tommy)
(repeat 3 figure02! tommy)
(turtle-set-color! tommy "orange")
(repeat 3 figure02! tommy)
(repeat 3 figure02! tommy)
(repeat 3 figure02! tommy)
(repeat 3 figure02! tommy)
(repeat 3 figure02! tommy)
(turtle-set-color! tommy "aqua")
(repeat 3 figure02! tommy)
(repeat 3 figure02! tommy)
(repeat 3 figure02! tommy)
(repeat 3 figure02! tommy)
(turtle-set-color! tommy "yellow")
(repeat 3 figure02! tommy)
(repeat 3 figure02! tommy)
(repeat 3 figure02! tommy)
(repeat 3 figure02! tommy)
(turtle-set-color! tommy "hotpink")
(repeat 3 figure02! tommy)
(repeat 3 figure02! tommy)
